import Image from 'next/image';
import React from 'react';

function Gallery() {
	return (
		<div>
			<div className="flex flex-wrap space-x-2 space-y-2 ">
				<Image
					width={250}
					height={150}
					src="/1.png"
					alt="photography"
					className="object-none"
				/>
				<Image
					width={220}
					height={150}
					src="/2.png"
					alt="photography"
					className="object-none"
				/>
				<Image
					width={250}
					height={150}
					src="/3.png"
					alt="photography"
					className="object-none"
				/>
				<Image
					width={220}
					height={150}
					src="/4.png"
					alt="photography"
					className="object-none"
				/>
				<Image
					width={250}
					height={150}
					src="/5.png"
					alt="photography"
					className="object-none"
				/>
				<Image
					width={220}
					height={150}
					src="/6.png"
					alt="photography"
					className="object-none"
				/>
				{/* 2 */}
				<Image
					width={130}
					height={200}
					src="/7.png"
					alt="photography"
					className="object-none"
				/>
				<Image
					width={350}
					height={200}
					src="/8.png"
					alt="photography"
					className="object-none"
				/>
				<Image
					width={355}
					height={200}
					src="/9.png"
					alt="photography"
					className="object-none"
				/>
				<Image
					width={130}
					height={200}
					src="/10.png"
					alt="photography"
					className="object-none"
				/>
				<Image
					width={250}
					height={150}
					src="/11.png"
					alt="photography"
					className="object-none"
				/>
				<Image
					width={230}
					height={150}
					src="/12.png"
					alt="photography"
					className="object-none"
				/>

				{/* 3 */}
				<Image
					width={250}
					height={150}
					src="/13.png"
					alt="photography"
					className="object-none"
				/>

				<Image
					width={220}
					height={150}
					src="/14.png"
					alt="photography"
					className="object-none"
				/>
				<Image
					width={250}
					height={150}
					src="/15.png"
					alt="photography"
					className="object-none"
				/>
				<Image
					width={220}
					height={150}
					src="/16.png"
					alt="photography"
					className="object-none"
				/>
				<Image
					width={370}
					height={150}
					src="/17.png"
					alt="photography"
					className="object-none"
				/>
				<Image
					width={200}
					height={220}
					src="/18.png"
					alt="photography"
					className="object-none"
				/>
				<Image
					width={220}
					height={150}
					src="/19.png"
					alt="photography"
					className="object-none"
				/>
				<Image
					width={250}
					height={150}
					src="/20.png"
					alt="photography"
					className="object-none"
				/>
				<Image
					width={220}
					height={150}
					src="/21.png"
					alt="photography"
					className="object-none"
				/>
				<Image
					width={250}
					height={150}
					src="/22.png"
					alt="photography"
					className="object-none"
				/>
				<Image
					width={220}
					height={150}
					src="/23.png"
					alt="photography"
					className="object-none"
				/>
				<Image
					width={230}
					height={150}
					src="/24.png"
					alt="photography"
					className="object-none"
				/>
			</div>
		</div>
	);
}

export default Gallery;
